const jobs = [
    'Mechanical Engineer',
    'Systems Analyst',
    'Customer Service Representative',
    'Physical Therapist',
    'Police Officer',
    'Budget analyst',
    'Zoologist',
    'Carpenter',
    'Janitor',
    'Recreation & Fitness Worker',
    'Food Scientist',
    'Epidemiologist',
    'Firefighter',
    'Farmer',
    'Actuary',
    'Psychologist',
    'Painter',
    'Construction Manager',
    'Lawyer',
    'Cashier',
    'Paramedic',
    'Editor',
    'Civil Engineer',
    'Medical Assistant',
    'Photographer',
    'Writer',
    'Electrician',
    'Sports Coach',
    'Logistician',
    'Mathematician',
    'Bookkeeping clerk',
    'Marketing Manager',
    'Software Developer',
    'Surveyor',
    'Chef',
    'Actor',
    'Economist',
    'Occupational Therapist',
    'Anthropologist',
    'Insurance Agent',
    'Personal Care Aide',
    'Computer Hardware Engineer',
    'Computer Support Specialist',
    'Electrical Engineer',
    'Chemist',
    'Substance Abuse Counselor',
    'Desktop publisher',
    'Plumber',
    'Statistician',
    'Automotive mechanic',
    'Pharmacist',
    'Teacher Assistant',
    'Physicist',
    'Web Developer',
    'Cost Estimator',
    'Middle School Teacher',
    'Bus Driver',
    'Computer Systems Analyst',
    'Recreational Therapist',
    'Physician',
    'Market Research Analyst',
    'Educator',
    'Patrol Officer',
    'Medical Secretary',
    'Diagnostic Medical Sonographer',
    'Landscaper & Groundskeeper',
    'Security Guard',
    'Marriage & Family Therapist',
    'School Counselor',
    'Social Worker',
    'Database administrator',
    'Environmental scientist',
    'Housekeeper',
    'Microbiologist',
    'Dentist',
    'IT Manager',
    'Reporter',
    'HR Specialist',
    'Real Estate Agent',
    'Mason',
    'Interpreter & Translator',
    'Coach',
    'Human Resources Assistant',
    'Radiologic Technologist',
    'Massage Therapist',
    'Landscape Architect',
    'Dental Hygienist',
    'Computer Programmer',
    'Respiratory Therapist',
    'Computer Systems Administrator',
    'Designer',
    'Executive Assistant',
    'Maintenance & Repair Worker',
    'Elementary School Teacher',
    'Receptionist',
    'Professional athlete',
    'Auto Mechanic',
    'Fitness Trainer',
    'Registered Nurse',
    'Paralegal',
    'Dancer',
    'Artist',
    'Public Relations Specialist',
    'Preschool Teacher',
    'Court Reporter',
    'Event Planner',
    'Musician',
    'Referee',
    'Secretary',
    'Clinical Laboratory Technician',
    'Loan Officer',
    'Childcare worker',
    'Drafter',
    'Librarian',
    'High School Teacher',
    'Urban Planner',
    'Accountant',
    'Hairdresser',
    'Veterinarian',
    'Architect',
    'Truck Driver',
    'Financial Advisor',
    'Compliance Officer',
    'School Psychologist',
    'Speech - Language Pathologist',
    'Historian',
    'Art Director',
    'Telemarketer',
    'Judge',
    'College Professor',
    'Product Manager',
];

export function getRandomJob() {
    const randomIndex = Math.random() * jobs.length;
    return jobs.at(randomIndex);
}

export default getRandomJob;
